### ISSUE TITLE
small fixes

### ISSUE THREAD

**Issue by l-kaplan** [wasimaftab/WeiseEule-LocalHost#1]
Dear BMC compbio thanks for the interesting software, I am very excited to try it out some more! I think it will make literature research much more efficient.

The installation was very easy on my Ubuntu machine and went flawlessly. Unfortunately I came upon two errors, that I think are easy to fix. 
1. When starting up the app I got this error message: 

> Traceback (most recent call last):
[2]   File "/home/lk/miniforge3/envs/qa_env/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
[2]     self.run()
[2]   File "/home/lk/miniforge3/envs/qa_env/lib/python3.10/multiprocessing/process.py", line 108, in run
[2]     self._target(*self._args, **self._kwargs)
[2]   File "/home/lk/miniforge3/envs/qa_env/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
[2]     target(sockets=sockets)
[2]   File "/home/lk/miniforge3/envs/qa_env/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
[2]     return asyncio.run(self.serve(sockets=sockets))
[2]   File "/home/lk/miniforge3/envs/qa_env/lib/python3.10/asyncio/runners.py", line 44, in run
[2]     return loop.run_until_complete(main)
[2]   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
[2]   File "/home/lk/miniforge3/envs/qa_env/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
[2]     await self._serve(sockets)
[2]   File "/home/lk/miniforge3/envs/qa_env/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
[2]     config.load()
[2]   File "/home/lk/miniforge3/envs/qa_env/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
[2]     self.loaded_app = import_from_string(self.app)
[2]   File "/home/lk/miniforge3/envs/qa_env/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
[2]     module = importlib.import_module(module_str)
[2]   File "/home/lk/miniforge3/envs/qa_env/lib/python3.10/importlib/__init__.py", line 126, in import_module
[2]     return _bootstrap._gcd_import(name[level:], package, level)
[2]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[2]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[2]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[2]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[2]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[2]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[2]   File "/home/lk/work/tools/WeiseEule-LocalHost/pycodes/fastapi_app.py", line 10, in <module>
[2]     import pycodes.PMC_downloader_Utils as pmcd
[2]   File "/home/lk/work/tools/WeiseEule-LocalHost/pycodes/PMC_downloader_Utils.py", line 53, in <module>
[2]     email=os.environ['EMAIL']
[2]   File "/home/lk/miniforge3/envs/qa_env/lib/python3.10/os.py", line 680, in __getitem__
[2]     raise KeyError(key) from None
[2] KeyError: 'EMAIL'

This was fixed when I changed line 54 in **PMC_downloader_Utils.py**
from `email=os.environ['EMAIL']` to my actual email address.

2. When fetching articles, the push to pinecone failed:

> 2024-10-18 10:20:22 - weiseeule_logger - CRITICAL - Error pushing the vectors in to pinecone, actual exception is: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'content-type': 'text/plain; charset=utf-8', 'access-control-allow-origin': '*', 'vary': 'origin,access-control-request-method,access-control-request-headers', 'access-control-expose-headers': '*', 'x-pinecone-api-version': '2024-04', 'X-Cloud-Trace-Context': '7adf4c03a10f22cd9212c856aa22b9d7', 'Date': 'Fri, 18 Oct 2024 17:20:22 GMT', 'Server': 'Google Frontend', 'Content-Length': '94', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'})
HTTP response body: {"error":{"code":"NOT_FOUND","message":"Resource namespaces-in-paper not found"},"status":404}

This was fixed when I changed line 853 in **PMC_downloader_Utils.py**
from `index = pc.Index('namespaces-in-paper')` to `index = pc.Index(os.environ['PINECONE_INDEX'])`

After fixing these issues it seems to work. I was able to create a namespace with few keywords limited to papers published between 2000 and 2024. Asking a question seemed to work, too. 
However, when I increased the time frame to range from 1980 to today, the fetch articles request never finishes. Do you think it might be too many papers to go through?

Let me know if you're interested in the log file. 

Greetings from Seattle, 
Lew

**Comment by l-kaplan** [comment]
I am not sure, but I think I found out why it never finished. I think when I used more keywords, the construction of the search term is disadvantageous.
In line 252 in **PMC_downloader_Utils.py**, all the keywords are put in quotes via `f'("{keywords}"[Title/Abstract])'`.
I tried using the constructed search term in the PubMed website and it complained about the quotes:

> Quoted phrase not found in [phrase index](https://pubmed.ncbi.nlm.nih.gov/help/#phrase-index): "retina development glia"

I don't know whether the search via their website and via the API works the same but, removing these quotes like so `f'({keywords}[Title/Abstract])'` seemed to resolve the problem of fetching articles for namespace creation.

**Comment by wasimaftab** [comment]
Dear Lew,

Thank you for testing the software. I have fixed the error corresponding to the pinecone index in PMC_downloader_Utils.py.   The `email=os.environ['EMAIL']` was not an error. In the present version, the email is taken from the .bashrc file.  For the other issue "fetch articles request never finishes", it would be great if you share your log and/or the list of keywords, date range etc.

Best regards,
Wasim

**Comment by l-kaplan** [comment]
Regarding the email: I see, that makes sense. But then you should add instructions in the installation guide to add the email as an environmental variable.

I attached the logs.


- [241018_fastAPI.log](https://github.com/user-attachments/files/17721028/241018_fastAPI.log):
    - you can see that the first namespace creation works (starting 2024-10-18 10:58:13) but then fails with other keywords (after 2024-10-18 11:17:47)


- [241022_fastAPI.log](https://github.com/user-attachments/files/17721024/241022_fastAPI.log) 
    
    -  namespace creation works after I made the changes mentioned above (2024-10-22 10:54:20)
    - But it also shows another problem I forgot to mention which seems to be related to exotic encoding of some papers (2024-10-22 11:16:58). This problem is solved when I set `silent_errors=True` in the DirectoryLoader
  
https://github.com/wasimaftab/WeiseEule-LocalHost/blob/cf5125f5c5143baa6acb7d60c915f2ba9739ae35/pycodes/PMC_downloader_Utils.py#L1065-L1068

`loader = DirectoryLoader('./' + data_dir + '/', glob='**/abstract*.txt',silent_errors=True, use_multithreading=True)`

I hope this helps.
